#+TITLE: org-pelican -- org-mde exporter for pelican

org-pelican is an org-mode exporter for [[https://github.com/getpelican/pelican][pelican]] static site generator.

This project is under *EXPERIMENTAL* state and used by [[https://github.com/coldnew/emacs-blogit][emacs-blogit]] project,
currently it only suppport generate =HTML= file to let pelican parse it.


* Features

- [X] Gravatar

  Generate metadata for =author_gravatar= so it's no need to install =gravatar=
  pelican plugins.

- [X] Table of contains

  Generate metadata for =toc=, which compatible with most pelican theme and it's
  no need to use [[https://github.com/ingwinlu/pelican-toc][pelican-toc]] plugin.

- [ ] Fancybox

  Convert image link with fancybox support automatically.

* Pelican plugins support

org-pelican also add pelican plugins support, which add following features.

- [X] Copy .org source in =contents= folder

  If you publish .org file with generate pelican html/md file, you can use
  org-pelican plugin to copy .org file to output folder.
